[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_project = "6Kygvz3eQNRHDypUBk7JEArupFUu6Py7yPEgP8ceavKJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/kaimatzu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
